version: '3.8'

services:
  nuxt-frontend:
    build: .
    ports:
      - "${PORT:-3000}:3000"  # Map PORT (default 3000) to Nuxt's internal port 3000
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - HOST=0.0.0.0  # Ensure Nuxt listens on all network interfaces
      - PORT=3000     # Set Nuxt’s internal port to 3000
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE:-http://localhost:3000}  # Use a fallback directly
    restart: unless-stopped